
FROM python:3.11-slim


COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/


WORKDIR /app

COPY pyproject.toml uv.lock ./


RUN uv sync --frozen --no-install-project --no-dev


COPY . .

# Set default MySQL environment variables for Docker
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=rootpassword
ENV MYSQL_HOST=db
ENV MYSQL_PORT=3306
ENV MYSQL_DB=files_db

EXPOSE 8000


CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

