import schemas
from fastapi import FastAPI, HTTPException, Depends, status
from fastapi.security import HTTPBasic, HTTPBasicCredentials
from typing import List
from pydantic import BaseModel
from sqlmodel import Session, select, create_engine, SQLModel
from dotenv import load_dotenv
import os

load_dotenv()

app = FastAPI()

security = HTTPBasic()

# --- Authenticaton layer for user ---
def verify_credentials(credentials: HTTPBasicCredentials = Depends(security)):
    correct_username = os.getenv("ADMIN_USER")
    correct_password = os.getenv("ADMIN_PASSWORD")
    if credentials.username != correct_username or credentials.password != correct_password:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect email or password",
            headers={"WWW-Authenticate": "Basic"},
        )
    return credentials.username

# ---- Database connection initial setup ----
sqlite_file_name = "database.db"
sqlite_url = f"sqlite:///{sqlite_file_name}"
engine = create_engine(sqlite_url)

def get_session():
    with Session(engine) as session:
        session.add()           # Prepare to save
        session.commit()        # Save changes to the file
        session.refresh()       # Get the new ID generated by the DB


@app.get("/")
def main(depends=verify_credentials):
    
    return "Hello from project1!"



if __name__ == "__main__":
    main()
